pipeline {

    agent any   

    stages {

        stage('Dotnet Steps') {
            agent {
                docker {
                    image 'mcr.microsoft.com/dotnet/sdk:9.0'
                    args '-u root:root'
                }
            }

            stages {
                stage('Restore') {
                    steps {
                        dir('RoomReservationSystem-copy') {
                            sh 'dotnet restore RoomReservationSystem.sln'
                        }
                    }
                }

                stage('Build') {
                    steps {
                        dir('RoomReservationSystem-copy') {
                            sh 'dotnet build RoomReservationSystem.sln --configuration Release'
                        }
                    }
                }

                stage('Test') {
                    steps {
                        dir('RoomReservationSystem-copy') {
                            sh 'dotnet test RoomReservationSystem.Tests/RoomReservationSystem.Tests.csproj'
                        }
                    }
                }
            }
        }

        stage('Build Docker Image') {
            steps {
                sh '''
                    docker build \
                      -f RoomReservationSystem-copy/RoomReservationSystem/Dockerfile \
                      -t roomreservation:latest \
                      RoomReservationSystem-copy
                '''
            }
        }
    }
}
